services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npx", "elm", "reactor"]
    ports:
      - 8080:8000
    user: 1000:1000
    volumes:
      - ./src/:/home/node/app/src/:ro
